/*
 * MIT License
 * 
 * Copyright (c) 2020 Sly Technologies Inc.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.easylibs.streamer.sql;

import java.sql.Connection;
import java.util.Optional;
import java.util.function.Consumer;

import org.easylibs.streamer.builder.StreamerBuffer;
import org.easylibs.streamer.sql.SqlInsert.Builder;
import org.easylibs.streamer.sql.util.SqlUtils;

/**
 * 
 * @author Mark Bednarczyk [repo@slytechs.com]
 */
class InsertBuilderImpl extends SqlBuilder<InsertBuilderImpl.Keyword, SqlInsert> implements Builder {

	enum Keyword {
		INSERT_INTO,
		COLUMNS,
		VALUES
	}

	private Connection connection;
	private final SqlDialect dialect;
	private Optional<Consumer<String>> sqlAction = Optional.empty();

	/**
	 * 
	 */
	public InsertBuilderImpl(SqlDialect dialect, Connection connection, String tableReference) {
		this.dialect = dialect;
		this.connection = connection;

		set(Keyword.INSERT_INTO, tableReference);
	}

	/**
	 * @see org.easylibs.streamer.sql.SqlInsert.Builder#build()
	 */
	@Override
	public SqlInsert build() {
		final String sql = buildSql();

		return new InsertImpl(connection, sql);
	}

	/**
	 * @see org.easylibs.streamer.sql.SqlBuilder#buildSql()
	 */
	@Override
	public String buildSql() {

		final StreamerBuffer body = new StreamerBuffer();
		final StreamerBuffer indented = body.newIndentedBuffer();

		body.setKeywordParser(SqlUtils::replaceUnderscores);
		body.enableFormatter(true);

		required(Keyword.INSERT_INTO)
				.header(body::section)
				.forEach(indented::printd);

		body.ln();
		optional(Keyword.COLUMNS)
				.forEach(indented::println);

		required(Keyword.VALUES)
				.header(body::sectionln)
				.before(indented::setDelimiter, ", ")
				.forEach(indented::printd);

		final String sql = body.asString();

		sqlAction.ifPresent(action -> action.accept(sql));

		return sql;
	}

	/**
	 * @see org.easylibs.streamer.sql.SqlInsert.Builder#columns(java.lang.String,
	 *      java.lang.String[])
	 */
	@Override
	public Builder columns(String column, String... columns) {
		set(Keyword.COLUMNS, dialect.groupColumns(column, columns));

		return this;
	}

	public Builder peekSql(Consumer<String> action) {
		this.sqlAction = Optional.ofNullable(action);

		return this;
	}

	/**
	 * @see org.easylibs.streamer.sql.SqlInsert.Builder#values(java.lang.String,
	 *      java.lang.String[])
	 */
	@Override
	public Builder values(Object value, Object... values) {
		add(Keyword.VALUES, dialect.groupValues(value, values));

		return this;
	}

	/**
	 * @see org.easylibs.streamer.sql.SqlUpdate.Builder#execute()
	 */
	@Override
	public int execute() {
		final SqlInsert update = build();

		return update.execute();
	}

	@Override
	public PreparedSqlUpdate prepare(boolean autoGeneratedKeys) {
		final SqlInsert insert = build();

		return insert.prepare(autoGeneratedKeys);
	}

}
